### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by nirev** [bugsnag-elixir/bugsnag-elixir#104]
Due to the async nature of the reporter, testing the app requires no async tests and sending messages between process. However currently the project has intermittent test failures.

**Comment by nathan-cruz77** [comment]
Hey @nirev, I believe I've found the issue with the tests.

This test is leaving a dangling task in `Bugsnag.TaskSupervisor`
https://github.com/bugsnag-elixir/bugsnag-elixir/blob/9bda40abd7b133834f9d7f6d6e1a606cc5f5ceb7/test/bugsnag_test.exs#L32-L38 and when it runs before any of the [logger tests](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/master/test/bugsnag/logger_test.exs), it causes `HTTPMock` to be called twice in the same test which breaks Mox as only one expectation was setup. Once Mox is crashed all other tests fail.

I was able to reproduce it running:
```bash
mix test test/bugsnag/logger_test.exs test/bugsnag_test.exs --seed 953177
```

I see three alternatives here:
1. Ensure tasks are terminated after each test in `BugsnagTest`;
2. Clean up pending tasks before running the tests in `Bugsnag.LoggerTest`
3. Use [`Bugsnag.Reporter.sync_report/2`](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/9bda40abd7b133834f9d7f6d6e1a606cc5f5ceb7/lib/bugsnag/reporter.ex#L34) in [the test](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/9bda40abd7b133834f9d7f6d6e1a606cc5f5ceb7/test/bugsnag_test.exs#L32-L38) instead of the asynchronous version.

I've tested these alternatives and had positive results. Besides passing with the seed I let the whole test suite run for about 30 minutes locally with each to ensure they work.

What do you think?
