### ISSUE TITLE
Elixir Umbrella application

### ISSUE THREAD

**Issue by Ciboulette** [bugsnag-elixir/bugsnag-elixir#57]
Hello, 

I'm using this package for a simple elixir application in production which is working well.

I'm currently building an umbrella application project - it doesn't seem to report uncaught exception - It's working when I send exception manually. Does anyone have an idea? 

Best regards :)

**Comment by BlueHotDog** [comment]
Same issue here.
Wondering if the project is still alive.. a couple of long standing PRs

**Comment by coburncoburn** [comment]
@Ciboulette @BlueHotDog can you explain more how the umbrella app is configured? Which app in the umbrella has the dependency on BugSnag? which is crashing?

**Comment by BlueHotDog** [comment]
Sure, the umbrella app is A. i've two apps inside B,C.
B has bugsnag as a dep, and i've added a test crash code ```:a=:b```. Nothing happens
While debugging the extension it seems like it goes to the catch-all def in the end of the logger..

**Comment by BlueHotDog** [comment]
Hey guys, still trying to make it work.. please help. do you need a PR?

**Comment by grantovich** [comment]
@BlueHotDog If you've found the root cause and are in a good position to open a PR, that would be great! If not, I think it would help tremendously if we had either a failing test case (although I'm not sure myself how you'd reproduce an umbrella project within the test suite), or a minimal reproduction (like a repo containing only the output of `mix new test_app --umbrella` plus the minimum changes required to demonstrate the issue).

**Comment by Ciboulette** [comment]
I've still the problem... 

I've tried to add the bugsnag dependency in every apps, it doesn't send uncaught exception to the Bugsnag service.. If I run manually:

```
# Report an exception.
try do
  :foo = :bar
rescue
  exception -> Bugsnag.report(exception)
end
```
it works

**Comment by grantovich** [comment]
@Ciboulette As mentioned above, I think we need either a failing test case or a minimal reproduction of this issue to investigate it further. I'm currently using bugsnag-elixir in an umbrella project myself and it seems to be reporting uncaught exceptions without any manual calls, so I don't think the issue is purely due to having an umbrella project.

I would also check #64 and ensure you're not encountering that one.

**Comment by Ciboulette** [comment]
Maybe the best is that you create a rapid demo umbrella repository which runs great with bugsnag handler.

**Comment by Ciboulette** [comment]
Nobody can help on this ?
